/**
 * docs/waiting-on-you.md — the backlog cut down to what only the owner can
 * move, with pictures of each open choice, for reading in Obsidian.
 *
 * docs/backlog.md holds every open item in full and answers "what is open?".
 * This note answers a narrower question — "what is waiting on me, and what does
 * each choice look like?" — so it leads with the open decisions, each with its
 * recommendation and the pictures from its options page, then the checks only
 * a person can do, then the rest of the owner's items one line each.
 *
 * It is built from the same registers as the backlog (tasks.mjs's payload) plus
 * two things only it uses: the pictures `make waiting-shots` takes of each
 * options page, and the recommendation line in each decision's record. All
 * three go into the hash stamped at the top, and gate-tasks refuses a note
 * whose stamp no longer matches, so it cannot quietly fall behind.
 *
 * Shared by the builder (build-waiting-doc.mjs), the camera (shoot-waiting.mjs)
 * and the check (gate-tasks.mjs).
 */
import { existsSync, readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { ROOT } from "./code-pointers.mjs";

export const WAITING_PATH = join(ROOT, "docs", "waiting-on-you.md");
export const WAITING_SHOTS_DIR = join(ROOT, "docs", "waiting-on-you");
export const WAITING_SHOTS_INDEX = join(WAITING_SHOTS_DIR, "shots.json");

/**
 * { decisionId: { shots: [{ file, caption }] } } from the last
 * `make waiting-shots`, or {} before the first.
 */
export function readShots() {
  if (!existsSync(WAITING_SHOTS_INDEX)) return {};
  return JSON.parse(readFileSync(WAITING_SHOTS_INDEX, "utf8"));
}

/**
 * The recommendation a decision record makes, as one line of markdown, or null.
 *
 * Records say it three ways, and all three are read rather than asking every
 * record to change: a bold lead ("**Recommendation:** C. …", "**Recommended:**
 * …", including one inside a list item), or an option heading that ends
 * "— recommended". The first one found wins.
 */
export function recommendationFrom(markdown) {
  const lines = markdown.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const heading = /^#{2,4}\s+(.*?)\s+—\s+recommended\s*$/i.exec(lines[i]);
    if (heading) return capital(heading[1].trim());
    const lead = /^\s*(?:[-*]\s+)?\*\*Recommend(?:ed|ation)\b[^*]*\*\*\s*(.*)$/i.exec(lines[i]);
    if (!lead) continue;
    const para = [lead[1]];
    for (let j = i + 1; j < lines.length; j++) {
      const next = lines[j];
      if (!next.trim() || /^\s*[-*]\s+/.test(next) || /^#/.test(next)) break;
      para.push(next.trim());
    }
    return capital(para.join(" ").replace(/\s+/g, " ").trim());
  }
  return null;
}

/** "keep today's…" reads as a fragment in a callout; the callout wants a sentence. */
const capital = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/** The recommendation in each open decision's record, keyed by decision id. */
export function readRecommendations(decisions) {
  const out = {};
  for (const d of decisions) {
    if (!d.doc) continue;
    const file = join(ROOT, d.doc.replace(/#.*$/, ""));
    if (!existsSync(file)) continue;
    const rec = recommendationFrom(readFileSync(file, "utf8"));
    if (rec) out[d.id] = rec;
  }
  return out;
}

/** The first sentence of an item's text, without the bold title it may repeat. */
export function firstSentence(text, max = 240) {
  const plain = (text ?? "")
    .replace(/^\s*\*\*[^*]+\*\*\s*/, "")
    .replace(/\s+/g, " ")
    .trim();
  const cut = /^(.+?[.?!])(\s|$)/.exec(plain);
  const s = cut ? cut[1] : plain;
  return s.length > max ? `${s.slice(0, max - 1).trimEnd()}…` : s;
}

/** Prefix every line with "> " so a block sits inside an Obsidian callout. */
const quoted = (lines) => lines.map((l) => (l ? `> ${l}` : ">"));

/**
 * The note, as a string. Pure: every input is passed in, so a test can feed
 * it a made-up backlog and read what comes out.
 *
 *   p      — tasks.mjs payload() (decisions, checks, issues)
 *   shots  — readShots()
 *   recs   — readRecommendations(p.decisions)
 *   link   — issues.mjs linker(): item → [title, href relative to docs/]
 *   hash   — the stamp for the top of the file
 */
export function renderWaiting({ p, shots, recs, link, hash }) {
  const out = [];
  const w = (s = "") => out.push(s);
  const mine = p.issues.filter((i) => i.owner === "user");
  const open = mine.filter((i) => i.status !== "blocked");
  const blocked = mine.filter((i) => i.status === "blocked");

  w("%% generated by scripts/build-waiting-doc.mjs — do not edit; run `make tasks-doc` %%");
  w(`%% waiting-hash: ${hash} %%`);
  w();
  w("# What is waiting on you?");
  w();
  w(
    `**${p.decisions.length} choices** to make, **${p.checks.length} checks** only a person can do, ` +
      `**${open.length} questions** to answer, and **${blocked.length} items** stuck until something ` +
      "outside the code happens. Choices come first: each one holds up work that is ready to build.",
  );
  w();
  w(
    "Every item here is written somewhere else and copied in. To change one, edit it where it lives, then run " +
      "`make tasks-doc`. The full text of everything open, yours or not, is in [the backlog](backlog.md). " +
      "The pictures come from `make waiting-shots`.",
  );
  w();

  // ── Decisions ──────────────────────────────────────────────────────────────
  w(`## Which choices are waiting on you? — ${p.decisions.length}`);
  w();
  if (p.decisions.length === 0) {
    w("None. Every question this project has opened has an answer on record.");
    w();
  }
  for (const d of p.decisions) {
    w(`### ${d.question}`);
    w();
    for (const o of d.options) w(`- **${o.id}** — ${o.label}`);
    w();
    if (recs[d.id]) {
      w("> [!tip] Recommended");
      w(`> ${recs[d.id]}`);
      w();
    }
    const where = [];
    if (d.artifact) where.push(`[open the options page](${d.artifact})`);
    if (d.doc) where.push(`[read the record](${d.doc.replace(/^docs\//, "")})`);
    if (where.length) w(`To choose: ${where.join(" · ")}, then tell Claude which one.`);
    w();
    const pics = shots[d.id]?.shots ?? [];
    if (pics.length === 0) {
      w("*No pictures yet: run `make waiting-shots`.*");
      w();
      continue;
    }
    const [first, ...rest] = pics;
    w(`![${first.caption}](waiting-on-you/${first.file})`);
    w();
    if (rest.length) {
      w(`> [!example]- ${rest.length} more ${rest.length === 1 ? "picture" : "pictures"} from the page`);
      const body = [];
      for (const s of rest) body.push(`**${s.caption}**`, "", `![${s.caption}](waiting-on-you/${s.file})`, "");
      body.pop();
      for (const l of quoted(body)) w(l);
      w();
    }
  }

  // ── Checks ─────────────────────────────────────────────────────────────────
  w(`## What can only you check, by hand? — ${p.checks.length}`);
  w();
  w("A machine cannot judge whether a hop is true, how a screen reader sounds, or whether a page still");
  w("opens after a week offline. Each check says why it matters; open it for what you need and the steps.");
  w("`make validate CHECK=<name>` prints the full walk-through, and `make record` saves your answer.");
  w();
  for (const c of p.checks) {
    w(`### ${c.title}`);
    w();
    if (c.why) {
      w(firstSentence(c.why, 400));
      w();
    }
    const body = [];
    if (c.blocks.length) body.push(`**It unblocks:** ${c.blocks.join(", ")}`, "");
    if (c.needs.length) {
      body.push("**You need:**", "");
      for (const x of c.needs) body.push(`- ${x}`);
      body.push("");
    }
    if (c.steps.length) {
      body.push("**The steps, short:**", "");
      c.steps.forEach((s, k) => body.push(`${k + 1}. ${s}`));
      body.push("");
    }
    body.push(`Run it with \`make validate CHECK=${c.id}\`.`);
    w("> [!note]- What you need, and the steps");
    for (const l of quoted(body)) w(l);
    w();
  }

  // ── The rest ───────────────────────────────────────────────────────────────
  const line = (i) => {
    const [title, href] = link(i);
    w(`- **[${title}](${href})** — ${firstSentence(i.text)}`);
  };
  w(`## What questions are waiting on your answer? — ${open.length}`);
  w();
  w("Judgements about how the app should feel or what it is for. Each line opens the page the");
  w("question is written on.");
  w();
  for (const i of open) line(i);
  w();
  w(`## What is stuck until something outside the code happens? — ${blocked.length}`);
  w();
  w("A device to hold, a licence to read, a membership to buy. Each page says what the item waits on.");
  w();
  for (const i of blocked) line(i);
  w();
  return `${out.join("\n")}\n`;
}

/** Stable short hash of everything the note is built from. */
export function waitingHash(p, shots, recs) {
  return createHash("sha256").update(JSON.stringify({ p, shots, recs })).digest("hex").slice(0, 12);
}

/** The hash the note on disk was built from, or null. */
export function docWaitingHash() {
  try {
    const m = readFileSync(WAITING_PATH, "utf8").match(/%% waiting-hash: ([0-9a-f]+) %%/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}
